### ISSUE TITLE
Cannot apply rejudging because `todo < 0`

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#2163]
### Description of the problem
I've been running a bunch of rejudgings for a contest, and in between I sometimes ran into internal errors, e.g. due to #2162. Now I seem to have gotten in a weird state where I can't apply a (full contest) rejudging after it completed.

### Your environment
DOMjudge version 8.0.

### Steps to reproduce
Unclear exactly how to reproduce, but it likely involves running a rejudging, then hitting an internal error and then either ignoring or marking as resolved this internal error while the original rejudging was still open.

### Actual behaviour
In this state, I found
```
mysql> SELECT submitid,COUNT(*) AS cnt  FROM judging j WHERE rejudgingid = 80 AND endtime IS NOT NULL GROUP BY 1 HAVING cnt > 1;
+----------+-----+
| submitid | cnt |
+----------+-----+
|     1847 |   2 |
|     1916 |   2 |
|     1934 |   2 |
|     2022 |   2 |
+----------+-----+
4 rows in set (0.01 sec)
```
which means that due to the duplicate judgings attached to this rejudging for 4 submissions, at https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Service/RejudgingService.php#L406 `$done` becomes negative, hence the "apply" button won't show up.

**Comment by meisterT** [comment]
I think this is fixed at HEAD, can you get a dump of your database and try locally at HEAD?

**Comment by eldering** [comment]
Digging a bit deeper, I see that these 4 submissions have 2 valid judgings associated to them. One is from a previous, applied rejudging, the other not associated to a rejudging.
Note that I haven't manually modified the database up to this point.

**Comment by eldering** [comment]
> I think this is fixed at HEAD, can you get a dump of your database and try locally at HEAD?

I'll dump the DB. Trying locally at head is impossible since I'm on CentOS 8 with PHP 7.2, but I can try it on my own computer later.

**Comment by eldering** [comment]
I've added a DB dump at `domjudge@domjudge.org:domjudge-2023-09-27-debug-rejudging_upgraded_dj82.sql.gz` to reproduce it, at least on `8.2` branch, which the dump is also for. I'll post the credentials in the #maintainer channel.

**Comment by eldering** [comment]
Also after migrating the data and code to current `main`, and restarting a new rejudging by doing a "Repeat rejudging" from rejudging 80, I still get at the end no apply button, only a cancel button, while there are no submissions left to rejudge.

**Comment by meisterT** [comment]
I have investigated this and opened multiple PRs to make this more robust / fix it.
